### ISSUE TITLE
mapping_stats.sh error

### ISSUE THREAD

**Issue by Melek-C** [FreBio/komics#1]
Dear colleagues when I run the mapping_stats.sh script using run2.mapped.sam as input it return this error:
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[main_samview] fail to read the header from "run2.mapped.sam".

Any solution?

Best

**Comment by FreBio** [comment]
Dear Melek,
It seems that your SAM file is truncated and is thus incomplete. Are you sure that the mapping job was entirely finished? It may be possible that the mapping job was killed prematurely due to e.g. wall time exceed.
Please let me know if the problem persists.
Best

**Comment by Melek-C** [comment]
Dear Frederik,

Here a snapshot of the head of the sam file

[cid:7f93c3a6-729f-4488-969d-38c841ed7c10]

Best

Melek Chaouch (Phd)
Postdoctoral Fellow
Institut Pasteur de Tunis
H3ABioNet Node Ambassador
***@***.***
***@***.***
Address: 13, Place Pasteur-B.P 74
1002 Tunis Belvédère

________________________________

**Comment by FreBio** [comment]
Hi Melek - it seems I can't open your attachment. Could you perhaps drop me an email at fvandenbroeck AT itg.be with the attachment?
If you like, you could also put a link (e.g. via dropbox or wetransfer) to your sam file so I can have a look at it. I think this would make it easier to help you.

Thanks
Fre
